# Epoch hyperparams
quantization_epochs: 3.0
freeze_bn: 2.0

# Learning rate hyperparams
init_lr: 1e-5


# Quantization Stage
quantization_modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: eval(quantization_epochs)

  - !QuantizationModifier
    start_epoch: 0.0
    freeze_bn_stats_epoch: eval(freeze_bn)

  - !SetLearningRateModifier
    start_epoch: 0.0
    learning_rate: eval(init_lr)
