name: "spexplusshort_gru_inference_test"
wandb_project: "ss"
resume: "/content/model_best_gru_cont2.pth"
n_gpu: 1
sr: 16000
log_step: 5
save_inference: True
save_dir: "inference_results"
dataset:
  sr: 16000
  inference:
    root: "./data/ss_dataset"
    part: "test"
    max_length: 10
    test_mode: True
    num_workers: 8
streamer:
  chunk_window: 4800
  chunk_step: 2400
  overlap_add_method: "half"
arch:
  type: "SpexPlusShortGRUModel"
  args: 
    n_channels: 256
    hidden_channels: 512
    out_channels: 100
    short_kernel: 40
    n_resnetblocks: 3
    n_stacked_tcnblocks: 4
    n_tcnblocks: 6
    dimension: "channels"
    n_speakers: 256
    causal: False
    memory_size: 128
inferencer:
  type: "ShortCausalInferencer"
  args: 
    type: "gru"
loss:
  type: "SpexPlusShortLoss"
  args: {}
metrics:
  - type: "SISDR"
    args: {}
  - type: "SNR"
    args: {}
  - type: "STOI"
    args: 
      fs: 16000
  - type: "CompositeMetric"
    args: {}
