name: "obt_test"
wandb_project: "ss"
resume: "../training/outputs/2024-04-22/10-43-45/model_best.pth"
n_gpu: 1
sr: 16000
log_step: 2
dataset:
  sr: 16000
  test:
    root: "../../data/ss_data_new/"
    part: "test"
    batch_size: 1
    n_speakers: 2
    max_length: 10
    num_workers: 2
    pin_memory: False
streamer:
  chunk_window: 4800
  chunk_step: 2400
  overlap_add_method: "half"
arch:
  type: "SpexPlusShort"
  args: 
    n_channels: 256
    hidden_channels: 512
    out_channels: 100
    short_kernel: 40
    n_resnetblocks: 3
    n_stacked_tcnblocks: 4
    n_tcnblocks: 5
    n_speakers: 921
    causal: False
loss:
  type: "SpexPlusShortLoss"
  args: {}
metrics:
  - type: "SISDR"
    args: {}
  - type: "SNR"
    args: {}
  - type: "STOI"
    args: 
      fs: 16000
  - type: "CompositeMetric"
    args: {}
