name: "one_batch_test_test"
wandb_project: "ss"
resume: "./outputs/2024-01-24/15-54-19/model_best.pth"
sr: 16000
n_speakers: 2
log_step: 1
input_dir: "./ss_data/test/"
output_dir: "./results/test/one_batch_test/"
arch:
  type: "SpexPlus"
  args: 
    n_channels: 64
    short_kernel: 40
    middle_kernel: 160
    long_kernel: 320
    n_resnetblocks: 3
    n_tcnblocks: 8
loss:
  type: "SpexPlusLoss"
  args: {}
metrics:
  - type: "SISDR"
    args: {}
  - type: "PESQ"
    args: {}
