name: "spexplus_test"
wandb_project: "online_target_source_separation"
resume: "../training/outputs/2024-04-05/11-29-26/model_best.pth"
n_gpu: 1
sr: 16000
n_speakers: 100
log_step: 500
dataset:
  sr: 16000
  test:
    root: "../../data/ss_data/"
    part: "test"
    batch_size: 1
    max_length: 1000000
    num_workers: 8
    pin_memory: False
arch:
  type: "SpexPlus"
  args: 
    n_channels: 256
    hidden_channels: 512
    out_channels: 100
    short_kernel: 40
    middle_kernel: 160
    long_kernel: 320
    n_resnetblocks: 3
    n_stacked_tcnblocks: 4
    n_tcnblocks: 8
loss:
  type: "SpexPlusLoss"
  args: {}
metrics:
  - type: "PESQ"
    args: {}
