name: "one_batch_test"
wandb_project: "ss"
n_gpu: 1
resume: "./outputs/2024-01-24/15-54-19/model_best.pth"
continue_from_checkpoint: False
dataset:
  sr: 16000
  train:
    root: "./ss_data/"
    part: "train"
    batch_size: 2
    max_length: 4
    num_workers: 2
    pin_memory: True
  dev:
    root: "./ss_data/"
    part: "dev"
    batch_size: 2
    max_length: 2
    num_workers: 2
    pin_memory: True
arch:
  type: "SpexPlus"
  args: 
    n_channels: 64
    short_kernel: 40
    middle_kernel: 160
    long_kernel: 320
    n_resnetblocks: 3
    n_tcnblocks: 8
optimizer:
  type: "Adam"
  args:
    lr: 0.01
    weight_decay: 0
loss:
  type: "SpexPlusLoss"
  args: {}
metrics:
  - type: "SISDR"
    args: {}
  - type: "PESQ"
    args: {}
  - type: "ACC"
    args: {}
train_metrics: ["SISDR", "PESQ", "ACC"]
dev_metrics: ["SISDR", "PESQ"]
trainer:
  trainer_batch_size: 2
  dataset_batch_size: 2
  epochs: 10
  save_period: 50
  monitor: "min dev_loss"
  early_stop: 6
  len_epoch: 2
