name: "one_batch_test_spexplusshortmodel_rnn"
wandb_project: "online_target_source_separation"
n_gpu: 1
dataset:
  sr: 16000
  train:
    root: "../../data/ss_data/"
    part: "train"
    batch_size: 2
    max_length: 4
    num_workers: 1
    pin_memory: True
  dev:
    root: "../../data/ss_data/"
    part: "dev"
    batch_size: 1
    max_length: 2
    num_workers: 1
    pin_memory: True
streamer:
  chunk_window: 4800
  chunk_step: 2400
  overlap_add_method: "half"
arch:
  type: "SpexPlusShortRNNModel"
  args: 
    n_channels: 64
    hidden_channels: 64
    out_channels: 10
    short_kernel: 40
    n_resnetblocks: 3
    n_stacked_tcnblocks: 4
    n_tcnblocks: 8
    rnn_type: "rnn"
    causal: False
optimizer:
  type: "Adam"
  args:
    lr: 0.01
    weight_decay: 0
loss:
  type: "SpexPlusShortLoss"
  args: {}
lr_scheduler:
  type: "ReduceLROnPlateau"
  args:
    factor: 0.5
    patience: 2
metrics:
  - type: "ACC"
    args: {}
train_metrics: ["ACC"]
dev_metrics: []
trainer:
  type: "ShortCausalTrainer"
  args: {}
  batch_size: 2
  epochs: 100
  save_period: 100
  monitor: "min loss"
  early_stop: 100
  grad_norm_clip: 60
