name: "spexplusshort_gru_version3"
wandb_project: "online_target_source_separation"
n_gpu: 2
resume: "./outputs/2024-05-04/01-09-47/model_best.pth"
continue_from_checkpoint: True
dataset:
  sr: 16000
  train:
    root: "../../data/data/ss_dataset"
    part: "train"
    batch_size: 8
    n_speakers: 256
    max_length: 20000
    num_workers: 8
    pin_memory: True
  dev:
    root: "../../data/data/ss_dataset"
    part: "dev"
    batch_size: 8
    max_length: 5000
    num_workers: 8
    pin_memory: True
streamer:
  chunk_window: 4800
  chunk_step: 2400
  overlap_add_method: "half"
arch:
  type: "SpexPlusShortGRUModel"
  args: 
    n_channels: 256
    hidden_channels: 512
    out_channels: 100
    short_kernel: 40
    n_resnetblocks: 3
    n_stacked_tcnblocks: 4
    n_tcnblocks: 6
    dimension: "channels"
    n_speakers: 256
    causal: False
    version: 3
    time_dim: 239
optimizer:
  type: "Adam"
  args:
    lr: 0.0003
    weight_decay: 0
loss:
  type: "SpexPlusShortLoss"
  args: {}
lr_scheduler:
  type: "ReduceLROnPlateau"
  args:
    factor: 0.5
    patience: 2
metrics:
  - type: "ACC"
    args: {}
train_metrics: ["ACC"]
dev_metrics: []
trainer:
  type: "ShortCausalTrainer"
  args: {}
  batch_size: 16
  epochs: 100
  save_period: 10
  monitor: "min dev_loss"
  early_stop: 6
  grad_norm_clip: 1000
