name: "spexplusshortrnn"
wandb_project: "online_target_source_separation"
n_gpu: 2
dataset:
  sr: 16000
  train:
    root: "../../data/ss_data/"
    part: "train"
    batch_size: 4
    max_length: 8000
    num_workers: 8
    pin_memory: True
  dev:
    root: "../../data/ss_data/"
    part: "dev"
    batch_size: 4
    max_length: 1000
    num_workers: 8
    pin_memory: True
streamer:
  chunk_window: 3200
  chunk_step: 1600
  overlap_add_method: "half"
arch:
  type: "SpexPlusShortRNN"
  args: 
    n_channels: 256
    hidden_channels: 512
    out_channels: 100
    short_kernel: 20
    n_resnetblocks: 3
    n_stacked_tcnblocks: 4
    n_tcnblocks: 8
    causal: False
optimizer:
  type: "AdamW"
  args:
    lr: 0.0001
    weight_decay: 0.00001
loss:
  type: "SpexPlusShortLoss"
  args: {}
lr_scheduler:
  type: "ReduceLROnPlateau"
  args:
    factor: 0.5
    patience: 2
metrics:
  - type: "ACC"
    args: {}
train_metrics: ["ACC"]
dev_metrics: []
trainer:
  type: "ShortCausalTrainer"
  args: {}
  batch_size: 4
  epochs: 100
  save_period: 10
  monitor: "min dev_loss"
  early_stop: 6
  grad_norm_clip: 40
