name: "spexplus_cont"
wandb_project: "online_target_source_separation"
n_gpu: 2
resume: "./outputs/2024-02-14/01-32-51/model_best.pth"
continue_from_checkpoint: True
dataset:
  sr: 16000
  train:
    root: "../../data/ss_data_with_silence_diff_snr/"
    part: "train"
    batch_size: 64
    max_length: 20000
    num_workers: 12
    pin_memory: True
  dev:
    root: "../../data/ss_data_new/"
    part: "dev"
    batch_size: 1
    max_length: 3000
    num_workers: 12
    pin_memory: True
arch:
  type: "SpexPlus"
  args: 
    n_channels: 256
    short_kernel: 40
    middle_kernel: 160
    long_kernel: 320
    n_resnetblocks: 3
    n_tcnblocks: 8
optimizer:
  type: "Adam"
  args:
    lr: 0.001
    weight_decay: 0
loss:
  type: "SpexPlusLoss"
  args: {}
lr_scheduler:
  type: "StepLR"
  args:
    step_size: 1
    gamma: 0.5
metrics:
  - type: "ACC"
    args: {}
train_metrics: ["ACC"]
dev_metrics: []
trainer:
  batch_size: 64
  epochs: 100
  save_period: 10
  monitor: "min dev_loss"
  early_stop: 6
  lr_scheduler_wait: 2
  len_epoch: 300
