name: "spexplusshort_gru_prune_60"
wandb_project: "online_target_source_separation"
n_gpu: 2
resume: "/kaggle/input/smaller-models/model_best-21.pth"
speaker_handler_name: "speaker_handler"
main_model_name: "main_model"
time_dim: 239
recipe_path: "./prunining_and_quantization/recipes/recipe_prune_60.yaml"
prune: True
quantize: False
dataset:
  sr: 16000
  train:
    root: "/kaggle/input/otss-dataset/data/ss_dataset"
    part: "train"
    batch_size: 4
    n_speakers: 256
    max_length: 20000
    num_workers: 8
    pin_memory: True
  dev:
    root: "/kaggle/input/otss-dataset/data/ss_dataset"
    part: "dev"
    batch_size: 4
    max_length: 5000
    num_workers: 8
    pin_memory: True
streamer:
  chunk_window: 4800
  chunk_step: 2400
  overlap_add_method: "half"
speaker_handler:
  n_channels: 192
  out_channels: 75
  short_kernel: 40
  n_resnetblocks: 3
  n_speakers: 256
main_model:
  n_channels: 192
  hidden_channels: 384
  out_channels: 75
  short_kernel: 40
  n_stacked_tcnblocks: 4
  n_tcnblocks: 6
  causal: False
  memory_size: 96
optimizer:
  type: "Adam"
  args:
    lr: 0.0001
    weight_decay: 0
loss:
  type: "SpexPlusShortLoss"
  args: {}
metrics:
  - type: "ACC"
    args: {}
train_metrics: ["ACC"]
dev_metrics: []
trainer:
  batch_size: 16
  epochs: 4
  grad_norm_clip: 1000
