audios_dir: "./LibriSpeech/"
audio_template: "*.flac"
random_state: 42
mix_generation_args:
  snr_levels: [0]
  num_workers: 2 
  update_steps: 50
  sr: 16000
  trim_db: 20
  vad_db: 20
  audio_len: 3
  ref_max_len: 7
train:
  part: "train-clean-100"
  out_folder: "./ss_data/train/"
  max_n_speakers: 101
  nfiles: 20000
  test: False
dev: 
  part: "dev-clean"
  out_folder: "./ss_data/dev/"
  nfiles: 5000
  test: True
test: 
  part: "test-clean"
  out_folder: "./ss_data/test/"
  nfiles: 3000
  test: True



