audios_dir: "../../data/LibriSpeech/"
audio_template: "*.flac"
random_state: 42
mix_generation_args:
  snr_levels: [0]
  num_workers: 10
  update_steps: 10
  sr: 16000
  trim_db: 20
  vad_db: 20
  audio_len: 3
  ref_max_len: 10
train:
  part: "train-clean-360"
  out_folder: "../../data/ss_data_360_many_speakers/train/"
  max_n_speakers: 1000
  nfiles: 7000
  test: False



