resume: "./model_best.pth"
num_iters: 100
mode: "gpu"
dataset:
  sr: 16000
  test:
    root: "./data/ss_dataset"
    part: "test"
    batch_size: 1
    max_length: 3000
    num_workers: 8
    pin_memory: False
streamer:
  chunk_window: 4800
  chunk_step: 2400
  overlap_add_method: "half"
arch:
  type: "SpexPlusShortGRUModel"
  args: 
    n_channels: 256
    hidden_channels: 512
    out_channels: 100
    short_kernel: 40
    n_resnetblocks: 3
    n_speakers: 256
    n_stacked_tcnblocks: 4
    n_tcnblocks: 6
    dimension: "channels"
    causal: False
    memory_size: 128
    version: 0

